### ISSUE TITLE
ExifGlass does not save the location of exiftool.exe

### ISSUE THREAD

**Issue by RPros** [d2phap/ExifGlass#8]
I have the MS Store version of ExifGlass 1.4.0.0 installed, I have exiftool.exe located in a set folder.  Using the ExifGlass -> Menu -> Settings -> I set the location of the Executable path.  Upon closing ExifGlass, the next run looses the executable path and defaults back to just exiftool.

- Note this issue also occurred in the previous version. 
- System is fully up to date Windows 10 and using the Microsoft Store purchased version of ExifGlass (latest version available - 1.4.0.0)

Can this either be fixed, or Is there a way to force the saving of the exiftool executable path?  either a config file or registry entry or other?

**Comment by d2phap** [comment]
Hi @RPros 
Thanks for the bug report. It's due [this breaking change in .NET 8](https://github.com/dotnet/docs/issues/37730) so ExifGlass failed to save the user settings.
I will publish an update soon; the Store version is going to take some time because of the approval process.

You can also change the exiftool path manually by opening ExifGlass config file located at:
`%LocalAppData%\ExifGlass\exifglass.config.json`:

![image](https://github.com/d2phap/ExifGlass/assets/3154213/956540d1-bc6c-4b8a-9d75-e8c69d098432)

**Comment by RPros** [comment]
Thank you for the reply.  I may have to wait until the next update.  There is no directory ExifGlass under %LocalAppData% (c:\Users\MYUSERNAME\AppData\Local\).  I manually created the directory and created a exifglass.config.json and populated it with your sample data (substituting the actual exiftool path), but it does not appear that ExifGlass then tries to open / use or save to the file.  Maybe the windows store version does not have the permissions to use the %LocalAppData% or is trying somewhere else.   I may try to just add the exiftool to my environment path as a possible workaround.  Thank you again and I look forward to the next update.

**Comment by d2phap** [comment]
Published new version!

**Comment by RPros** [comment]
Thank you so much.  Works perfectly and now saves the exiftool location.  Thanks again!
